export function invertRecord(record: Record<string, string>): Record<string, string> {
  return Object.fromEntries(Object.entries(record).map(([k, v]) => [v, k]));
}

// shared with /background.ts and /cgb-banners.content/assets/index.ts
export const SHOP_ID_TO_CODE: Record<string, string> = {
  2: 'UK',
  12: 'PL',
  1: 'CH',
  3: 'DE',
  8: 'AT',
  17: 'NL',
  7: 'FR',
  10: 'ES',
  22: 'PT',
  21: 'IT',
  25: 'DK',
  28: 'NO',
  27: 'FI',
  23: 'SE',
  26: 'CZ',
  29: 'SK',
  24: 'HU',
  30: 'RO',
  19: 'BE',
  33: 'HR',
  34: 'SI',
};

export const COUNTRY_CASHBACK: Record<string, string> = {
  'UK-PL': 'polish',
  UK: 'english',
  'SK-HU': 'Hungarian',
  'SK-EN': 'english',
  'SK-CZ': 'czech',
  SK: 'slovak',
  SE: 'swedish',
  'SE-EN': 'english',
  RO: 'romanian',
  'RO-EN': 'english',
  PT: 'portugal',
  'PT-EN': 'english',
  PL: 'polish',
  'PL-EN': 'english',
  NO: 'norsk',
  'NO-EN': 'english',
  'NL-FR': 'french',
  'NL-EN': 'english',
  NL: 'dutch',
  IT: 'italian',
  'IT-EN': 'english',
  HU: 'Hungarian',
  'HU-EN': 'english',
  FR: 'french',
  'FR-NL': 'dutch',
  'FR-DE': 'germanDE',
  'FR-EN': 'english',
  FI: 'finnish',
  'FI-EN': 'english',
  'FI-SE': 'swedish',
  ES: 'spanish',
  'ES-EN': 'english',
  DK: 'danish',
  'DK-EN': 'english',
  DEAT: 'germanDE',
  'DEAT-EN': 'english',
  CZ: 'czech',
  'CZ-EN': 'english',
  'CZ-SK': 'slovak',
  CH: 'german',
  'CH-EN': 'english',
  'CH-FR': 'french',
  'CH-IT': 'italian',
  'BE-DE': 'germanDE',
  'BE-EN': 'english',
  'BE-FR': 'french',
  'BE-NL': 'dutch',
  HR: 'croatian',
  'HR-EN': 'english',
  SI: 'slovene',
  'SI-EN': 'english',
};
