export const shopLanguageMap: Record<string, string[]> = {
  "1": ["german", "french"],
  "2": ["english"],
  "3": ["germanDE"],
  "7": ["french"],
  "8": ["germanDE"],
  "10": ["spanish"],
  "12": ["polish"],
  "17": ["dutch"],
  "19": ["dutch", "french"],
  "21": ["italian"],
  "22": ["portugal"],
  "23": ["swedish"],
  "24": ["Hungarian"],
  "25": ["danish"],
  "26": ["czech"],
  "27": ["finnish"],
  "28": ["norsk"],
  "29": ["slovak"],
  "30": ["romanian"],
  "33": ["croatian"],
  "34": ["slovene"],
};