export const TABLE_SHOP_ORDER = [
  'UK',
  'PL',
  'DE',
  'AT',
  'CHDE',
  'NL',
  'FR',
  'CHFR',
  'ES',
  'PT',
  'IT',
  'DK',
  'NO',
  'FI',
  'SE',
  'CZ',
  'SK',
  'HU',
  'BEFR',
  'BENL',
  'RO',
  'CHIT',
] as const;

export const NEWSLETTER_SHOP_ORDER = [
  'CHDE',
  'CHFR',
  'AT',
  'BENL',
  'BEFR',
  'CZ',
  'DE',
  'DK',
  'FI',
  'FR',
  'HU',
  'IT',
  'NL',
  'NO',
  'PL',
  'PT',
  'RO',
  'SE',
  'SK',
  'SP',
  'UK',
] as const;

export const LP_SHOPS_ORDER = [...NEWSLETTER_SHOP_ORDER] as const;

export const SHOP_ID_MAP: Record<string, number> = {
  CHDE: 1,
  CHFR: 1,
  UK: 2,
  DE: 3,
  FR: 7,
  AT: 8,
  ES: 10,
  SP: 10,
  PL: 12,
  NL: 17,
  BEFR: 19,
  BENL: 19,
  PT: 22,
  IT: 21,
  SE: 23,
  HU: 24,
  DK: 25,
  CZ: 26,
  FI: 27,
  NO: 28,
  SK: 29,
  RO: 30,
};

export const SHOP_DOMAIN_MAP: Record<string, string> = {
  CHDE: 'https://beliani.ch',
  CHFR: 'https://beliani.ch',
  UK: 'https://beliani.co.uk',
  DE: 'https://beliani.de',
  FR: 'https://beliani.fr',
  AT: 'https://beliani.at',
  SP: 'https://beliani.es',
  ES: 'https://beliani.es',
  PL: 'https://beliani.pl',
  NL: 'https://beliani.nl',
  BENL: 'https://beliani.be',
  BEFR: 'https://beliani.be',
  PT: 'https://beliani.pt',
  IT: 'https://beliani.it',
  SE: 'https://beliani.se',
  HU: 'https://beliani.hu',
  DK: 'https://beliani.dk',
  CZ: 'https://beliani.cz',
  FI: 'https://beliani.fi',
  NO: 'https://beliani.no',
  SK: 'https://beliani.sk',
  RO: 'https://beliani.ro',
};

export const LP_CHECKPOINT_TEMPLATES: Array<{ slug: string; shopId: number }> = LP_SHOPS_ORDER.map(slug => ({
  slug,
  shopId: SHOP_ID_MAP[slug],
})).filter(item => typeof item.shopId === 'number');

export const SHOP_ALIASES: Record<string, string> = {
  SP: 'ES',
};
